# Generated by Django 5.0.4 on 2026-06-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('charge_paisa', models.PositiveBigIntegerField()),
                ('free_delivery_threshold_paisa', models.PositiveBigIntegerField(blank=True, null=True)),
                ('delivery_estimate', models.CharField(max_length=120)),
                ('districts', models.TextField(blank=True, help_text='Comma-separated district names.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('charge_paisa', 'name'),
            },
        ),
    ]
