# Generated by Django 5.0.4 on 2026-06-22 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('awaiting_payment', 'Awaiting Payment'), ('payment_confirmed', 'Payment Confirmed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('ready_for_shipment', 'Ready for Shipment'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('failed_delivery', 'Failed Delivery')], default='placed', max_length=40)),
                ('subtotal_paisa', models.PositiveBigIntegerField()),
                ('discount_paisa', models.PositiveBigIntegerField(default=0)),
                ('delivery_charge_paisa', models.PositiveBigIntegerField(default=0)),
                ('payment_fee_paisa', models.PositiveBigIntegerField(default=0)),
                ('grand_total_paisa', models.PositiveBigIntegerField()),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('delivery_zone_name', models.CharField(blank=True, max_length=80)),
                ('estimated_delivery', models.CharField(blank=True, max_length=120)),
                ('idempotency_token', models.CharField(max_length=120, unique=True)),
                ('stock_reduced_at', models.DateTimeField(blank=True, null=True)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('alternative_phone', models.CharField(blank=True, max_length=32)),
                ('division', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('upazila', models.CharField(max_length=80)),
                ('area', models.CharField(max_length=120)),
                ('road', models.CharField(max_length=160)),
                ('house', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=160)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_snapshot', models.PositiveBigIntegerField()),
                ('variant_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=90)),
                ('variant_label', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=40)),
                ('colour', models.CharField(blank=True, max_length=60)),
                ('unit_price_paisa', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('image_reference', models.CharField(blank=True, max_length=240)),
                ('discount_paisa', models.PositiveBigIntegerField(default=0)),
                ('tax_paisa', models.PositiveBigIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('awaiting_payment', 'Awaiting Payment'), ('payment_confirmed', 'Payment Confirmed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('ready_for_shipment', 'Ready for Shipment'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('failed_delivery', 'Failed Delivery')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('visible_to_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
        ),
    ]
